import "./globals.css";
import { Inter } from "next/font/google";
import "./amplifyConfigureClient";
import "./amplifyConfigureServer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  console.log("ROOT LAYOUT", new Date());

  await Promise.resolve();

  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
